# Generated by Django 4.2.11 on 2024-03-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0002_rename_customer_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
