# Generated by Django 4.2.11 on 2024-03-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0007_remove_file_name_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='cez.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 19, 7, 24, 177167)),
        ),
    ]
