# Generated by Django 4.2.11 on 2024-03-25 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0007_degree_semester_alter_assignment_due_date_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cez.degree'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cez.semester'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 18, 23, 48, 964953)),
        ),
    ]
