# Generated by Django 4.2.11 on 2024-03-24 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0008_topic_assignments_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='topics',
            field=models.ManyToManyField(blank=True, to='cez.topic'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 21, 56, 47, 429547)),
        ),
    ]
