# Generated by Django 4.2.11 on 2024-03-24 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0009_assignment_topics_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 22, 30, 1, 574259)),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='assignments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cez.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='assignments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cez.assignment'),
        ),
    ]
