# Generated by Django 4.2.11 on 2024-03-24 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0010_alter_assignment_due_date_remove_assignment_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 22, 30, 12, 660358)),
        ),
    ]
