# Generated by Django 4.2.11 on 2024-03-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0011_remove_enrollment_first_time_joined_and_more'),
        ('cez', '0012_alter_assignment_due_date_remove_assignment_topics_and_more'),
    ]

    operations = [
    ]
