# Generated by Django 4.2.11 on 2024-03-25 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0013_merge_20240325_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, to='cez.topic'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 22, 34, 19, 604656)),
        ),
    ]
