# Generated by Django 4.2.11 on 2024-03-26 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_pic'),
        ('cez', '0014_course_topics_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 16, 27, 56, 584351)),
        ),
        migrations.CreateModel(
            name='RateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=1024)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cez.submission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
