# Generated by Django 4.2.11 on 2024-04-01 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0015_alter_assignment_due_date_ratesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 17, 59, 13, 819211)),
        ),
    ]
