# Generated by Django 4.2.11 on 2024-04-05 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0030_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 10, 41, 50, 70168)),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
