# Generated by Django 4.2.11 on 2024-04-05 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0031_alter_assignment_due_date_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 11, 19, 8, 521775)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='topic',
            name='files',
            field=models.ManyToManyField(blank=True, to='cez.coursefile'),
        ),
    ]
