# Generated by Django 4.2.11 on 2024-04-05 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0033_alter_assignment_due_date_alter_coursefile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 11, 30, 6, 17047)),
        ),
    ]
