# Generated by Django 4.2.11 on 2024-04-05 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0034_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 11, 33, 6, 454181)),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
