# Generated by Django 4.2.11 on 2024-04-15 18:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cez', '0038_alter_assignment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratesubmission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.ManyToManyField(blank=True, to='cez.submission'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ratesubmission',
            field=models.ManyToManyField(blank=True, to='cez.ratesubmission'),
        ),
        migrations.AddField(
            model_name='ratesubmission',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 20, 6, 46, 962506)),
        ),
        migrations.AlterField(
            model_name='course',
            name='access_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
