# Generated by Django 4.2.11 on 2024-04-15 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cez', '0039_remove_ratesubmission_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='ratesubmission',
        ),
        migrations.AddField(
            model_name='ratesubmission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cez.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cez.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 21, 37, 49, 246449)),
        ),
        migrations.AlterField(
            model_name='ratesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
