# Generated by Django 4.2.11 on 2024-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cez', '0040_alter_assignment_due_date_alter_course_teacher'),
        ('cez', '0040_remove_assignment_assignment_and_more'),
    ]

    operations = [
    ]
