# Generated by Django 4.2.11 on 2024-03-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
